name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - name: Checkout notes repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TARGET_REPO }}
          token: ${{ secrets.ROAM_PERSONAL_ACCESS_TOKEN }}
          ref: master
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup dependencies
        run: |
          wget -qO /tmp/jet.zip https://github.com/borkdude/jet/releases/download/v0.0.13/jet-0.0.13-linux-amd64.zip
          unzip /tmp/jet.zip -d /tmp
          sudo mv /tmp/jet /usr/local/bin/jet
          pip install git+https://github.com/gvteja/roam-to-git.git
      
      - name: Run backup
        id: backup
        continue-on-error: true
        run: |
          roam-to-git -f markdown formatted json edn -- .
        env:
          ROAMRESEARCH_USER: ${{ secrets.ROAMRESEARCH_USER }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.ROAMRESEARCH_PASSWORD }}
          ROAMRESEARCH_DATABASE: ${{ secrets.ROAMRESEARCH_DATABASE }}
          
      - name: Status report
        if: ${{ (success() || failure()) && steps.backup.outcome == 'success' }}
        run: |
          data=$(jq -n --arg dt "`date +%Y/%m/%d-%T`" '{lastSuccessTime: $dt}')
          echo $data
          curl -d "$data" -X PUT -H "Content-Type: application/json" -H "x-apikey: $DS_KEY" $DS_URL --write-out '%{http_code}' --silent --output /dev/null
        env:
          DS_URL: ${{ secrets.DS_URL }}
          DS_KEY: ${{ secrets.DS_KEY }}
