name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "1 1 1 * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - name: Checkout notes repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.targetRepo }}
          token: ${{ secrets.roamPat }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup dependencies
        run: |
          pip install git+https://github.com/gvteja/roam-to-git.git
      - name: Run backup
        run: |
          roam-to-git .
        env:
          ROAMRESEARCH_USER: ${{ secrets.roamEmail }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.roamPassword }}
          ROAMRESEARCH_DATABASE: ${{ secrets.roamDatabase }}
          
