name: "Roam Research backup"

on:
  push:
    branches:
      - master
  schedule:
    - cron: "*/5 * * * *"

jobs:
  backup:
    runs-on: ubuntu-latest
    name: Backup
    timeout-minutes: 15
    steps:
      - name: Checkout notes repo
        uses: actions/checkout@v2
        with:
          repository: ${{ secrets.TARGET_REPO }}
          token: ${{ secrets.ROAM_PERSONAL_ACCESS_TOKEN }}
          ref: master
      
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      
      - name: Setup dependencies
        run: |
          pip install git+https://github.com/gvteja/roam-to-git.git
      
      - name: Run backup
        continue-on-error: true
        run: |
          roam-to-git .
        env:
          ROAMRESEARCH_USER: ${{ secrets.ROAMRESEARCH_USER }}
          ROAMRESEARCH_PASSWORD: ${{ secrets.ROAMRESEARCH_PASSWORD }}
          ROAMRESEARCH_DATABASE: ${{ secrets.ROAMRESEARCH_DATABASE }}
          
      - name: Status report
        if: success()
        run: |
          curl hello
